### ISSUE TITLE
Fallback language problem

### ISSUE THREAD

**Issue by mpetricek** [tomekskuta/gatsby-starter-intl#2]
Hi,

I tried to use your gatsby starter now but after last update fallbacklang is not working right. It detects my browser language (cs) but doesn't fallback to "en". Not sure where is the problem.

Thank you

EDIT:

I'm stupid and I see that in build everything is ok. My bad and I'm sorry

**Comment by tomekskuta** [comment]
Wow! I just saw there is first issue on my first open source project! I can die now... ;p

@mpetricek  I'm happy you use it!
